### ISSUE TITLE
Performance Improvements 2: only use n-th image for inference

### ISSUE THREAD

**Issue by stefancyliax** [stefancyliax/CarND-Capstone#19]
optionally as rosparam

currently: ~5 hz

maybe every 2nd or 3rd image still works

**Comment by paul-michalik** [comment]
So how can the frequency depend on the ability of the subscriber to process messages at certain speed? Because this is the only factor influenced by the GPU available for TF…

Sent from my Windows 10 phone

**Comment by stefancyliax** [comment]
Good question. Probably caused by CPU bottlenecks?! The stxy server (or sim) does not have enough CPU time to publish with full frame rate?

**Comment by paul-michalik** [comment]
This shouldn’t be CPU bound… These bitrates are far below the capabilities of either hardware/OS combo. No idea, let's just work on pushing this out to the submission 😐

Sent from my Windows 10 phone

**Comment by stefancyliax** [comment]
I agree, doesn't really make sense. But from my testing it looks like there is a bottleneck with the message publishing. It look like it anyway. I had the car going of the street because I started another program in the background. 
And the fault in the waypoint_updater was a lot worse on the local machine than on the VM. In my theory because the thread sent more messages and something got congested on the message bus...

**Comment by stefancyliax** [comment]
@paul-michalik is it possible for you to implement this with minimal hassle? Would allow nice debugging and even every second image would be a big performance gain.

**Comment by paul-michalik** [comment]
Yes, this one is easy!
