### ISSUE TITLE
Vehicle does not recognize red lights

### ISSUE THREAD

**Issue by stefancyliax** [stefancyliax/CarND-Capstone#22]
Currently the car just goes through all red lights.
Topic /traffic_lights is always "-1".  

https://youtu.be/8RjeIt0tUkA

Am I doing something wrong?!

**Comment by paul-michalik** [comment]
Hm... Going to test this on a master branch. Which network have you used inception or mobile?

**Comment by paul-michalik** [comment]
Hm... Going to test this on a master branch. Which network have you used, inception or mobile?

**Comment by stefancyliax** [comment]
Happened with both networks. TF was initialized, it showed my 1060.

**Comment by stefancyliax** [comment]
Will test #23 this evening!

**Comment by stefancyliax** [comment]
Fixed with #23
